version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"

  - package-ecosystem: "swift"
    directory: "/Engine"
    schedule:
      interval: "weekly"

  - package-ecosystem: "swift"
    directory: "/Store"
    schedule:
      interval: "weekly"

  - package-ecosystem: "swift"
    directory: "/App"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
