import Foundation
import SwiftData

// MARK: - Frozen: the shapes version 1 shipped
//
// These seven classes are a historical record, not live code. Nothing in the app may construct or
// query them; the unqualified names (`StoredPrediction`, `ExploredCell`, …) mean V2's classes, and
// `SchemaVersionTests.testV1AndV2DeclareDistinctModelTypes` fails if these two sets ever collapse
// into one.
//
// **Do not edit this file.** A property added here silently changes the shape SwiftData believes
// installed stores were written at, which is how a lightweight migration starts failing on devices
// and nowhere else. `SchemaVersionTests.v1Shape` is the assertion that this stayed still.
//
// Why the duplication is unavoidable: `Schema(versionedSchema: CardCopilotSchemaV1.self)` derives
// entities from these types, so pointing V1 at the live classes would make V1 *report* V2's shape
// — and the V1→V2 migration test would then write a V2 store and open a V2 store, and pass while
// proving nothing. Nor can the six unchanged models be borrowed from V2: `StoredPrediction`,
// `StoredPurchase`, and `StoredObservation` form one relationship graph, and `ShoppingArea` and
// `AreaMember` another, so an inverse would point at a class outside the schema declaring it.
//
// Note on name resolution: unqualified `StoredPurchase` below means `CardCopilotSchemaV1`'s own
// member, not the module-level typealias — an enclosing type's members shadow module scope. That
// rule became load-bearing the moment V1 and V2 stopped being the same seven classes, so
// `SchemaVersionTests.testRelationshipsStayWithinTheirSchemaVersion` pins it at compile time.
extension CardCopilotSchemaV1 {

    /// V1's prediction row: no provenance. `contractRelease`, `contractDigest`, and `frozenInputs`
    /// arrive in V2 as nullable columns, which is what keeps that migration lightweight.
    @Model
    final class StoredPrediction {
        private(set) var id: UUID = UUID()
        private(set) var recordedAt: Date = Date()
        private(set) var merchantName: String = ""
        private(set) var merchantIdentifier: String?
        private(set) var predictedCategory: String = ""
        private(set) var confidenceSourceRaw: String = ConfidenceSource.fallback.rawValue
        private(set) var winnerCardId: String = ""
        private(set) var winnerValueCad: Double = 0
        private(set) var predictedRewardUnits: Double?
        private(set) var predictedRewardUnitKind: String?
        private(set) var defaultCardValueCad: Double?
        private(set) var winnerRuleId: String?
        private(set) var runnerUpCardId: String?
        private(set) var runnerUpValueCad: Double?
        private(set) var scoredAmountCad: Double?
        private(set) var valuationCentsPerPoint: Double?
        private(set) var headline: String = ""

        @Relationship(deleteRule: .cascade, inverse: \StoredPurchase.prediction)
        var purchase: StoredPurchase?

        init(merchantName: String, merchantIdentifier: String? = nil,
             predictedCategory: String, confidenceSource: ConfidenceSource,
             winnerCardId: String, winnerValueCad: Double,
             predictedRewardUnits: Double? = nil, predictedRewardUnitKind: String? = nil,
             defaultCardValueCad: Double? = nil, winnerRuleId: String? = nil,
             runnerUpCardId: String? = nil, runnerUpValueCad: Double? = nil,
             scoredAmountCad: Double? = nil, valuationCentsPerPoint: Double? = nil,
             headline: String, recordedAt: Date = Date()) {
            self.id = UUID()
            self.recordedAt = recordedAt
            self.merchantName = merchantName
            self.merchantIdentifier = merchantIdentifier
            self.predictedCategory = predictedCategory
            self.confidenceSourceRaw = confidenceSource.rawValue
            self.winnerCardId = winnerCardId
            self.winnerValueCad = winnerValueCad
            self.predictedRewardUnits = predictedRewardUnits
            self.predictedRewardUnitKind = predictedRewardUnitKind
            self.defaultCardValueCad = defaultCardValueCad
            self.winnerRuleId = winnerRuleId
            self.runnerUpCardId = runnerUpCardId
            self.runnerUpValueCad = runnerUpValueCad
            self.scoredAmountCad = scoredAmountCad
            self.valuationCentsPerPoint = valuationCentsPerPoint
            self.headline = headline
        }
    }

    @Model
    final class StoredPurchase {
        private(set) var id: UUID = UUID()
        private(set) var createdAt: Date = Date()
        var cardUsedId: String?
        var cardSourceRaw: String?
        var amountCad: Double?
        var amountSourceRaw: String?
        var completedAt: Date?
        var prediction: StoredPrediction?

        @Relationship(deleteRule: .cascade, inverse: \StoredObservation.purchase)
        var observation: StoredObservation?

        init(createdAt: Date = Date()) {
            self.id = UUID()
            self.createdAt = createdAt
        }
    }

    @Model
    final class StoredObservation {
        private(set) var id: UUID = UUID()
        private(set) var confirmedAt: Date = Date()
        private(set) var observedCategory: String = ""
        private(set) var observedRewardUnits: Double?
        private(set) var missClassRaw: String?
        private(set) var note: String?
        var purchase: StoredPurchase?

        init(observedCategory: String, observedRewardUnits: Double? = nil,
             missClass: MissClass? = nil,
             note: String? = nil, confirmedAt: Date = Date()) {
            self.id = UUID()
            self.confirmedAt = confirmedAt
            self.observedCategory = observedCategory
            self.observedRewardUnits = observedRewardUnits
            self.missClassRaw = missClass?.rawValue
            self.note = note
        }
    }

    @Model
    final class StoredMerchant {
        private(set) var id: UUID = UUID()
        private(set) var name: String = ""
        private(set) var identifier: String?
        var poiCategoryRaw: String?
        private(set) var latitude: Double = 0
        private(set) var longitude: Double = 0
        var confirmedCategory: String?
        var confirmationCount: Int = 0
        var lastSeenAt: Date = Date()

        init(name: String, identifier: String? = nil, poiCategoryRaw: String? = nil,
             latitude: Double, longitude: Double,
             confirmedCategory: String? = nil, confirmationCount: Int = 0,
             lastSeenAt: Date = Date()) {
            self.id = UUID()
            self.name = name
            self.identifier = identifier
            self.poiCategoryRaw = poiCategoryRaw
            self.latitude = latitude
            self.longitude = longitude
            self.confirmedCategory = confirmedCategory
            self.confirmationCount = confirmationCount
            self.lastSeenAt = lastSeenAt
        }
    }

    @Model
    final class ExploredCell {
        private(set) var cellKey: String = ""
        var exploredAt: Date = Date()
        var areaCount: Int = 0

        init(cellKey: String, exploredAt: Date, areaCount: Int) {
            self.cellKey = cellKey
            self.exploredAt = exploredAt
            self.areaCount = areaCount
        }
    }

    @Model
    final class ShoppingArea {
        private(set) var id: UUID = UUID()
        private(set) var cellKey: String = ""
        private(set) var centroidLatitude: Double = 0
        private(set) var centroidLongitude: Double = 0
        private(set) var radiusMeters: Double = 0
        var discoveredAt: Date = Date()

        @Relationship(deleteRule: .cascade, inverse: \AreaMember.area)
        var members: [AreaMember] = []

        init(cellKey: String, centroidLatitude: Double, centroidLongitude: Double,
             radiusMeters: Double, discoveredAt: Date) {
            self.id = UUID()
            self.cellKey = cellKey
            self.centroidLatitude = centroidLatitude
            self.centroidLongitude = centroidLongitude
            self.radiusMeters = radiusMeters
            self.discoveredAt = discoveredAt
        }
    }

    @Model
    final class AreaMember {
        private(set) var name: String = ""
        private(set) var identifier: String?
        private(set) var poiCategoryRaw: String?
        private(set) var latitude: Double = 0
        private(set) var longitude: Double = 0
        var area: ShoppingArea?

        init(name: String, identifier: String?, poiCategoryRaw: String?,
             latitude: Double, longitude: Double) {
            self.name = name
            self.identifier = identifier
            self.poiCategoryRaw = poiCategoryRaw
            self.latitude = latitude
            self.longitude = longitude
        }
    }
}
